### PR TITLE
Fix video frame conversion by adding 32-byte alignment to output buffer linesizes

### LINKED ISSUE #12: Certain video dimensions cause incomplete frame decoding or buffer overflow during YUV-to-RGB conversion
# What

For certain video dimensions where the video is encoded in YUV format, `sws_scale` in `AVProcessVideoFrame` will sometimes skip the rightmost pixels in each row of the output image, causing a portion of the image to be cut off. Other times it'll write extra pixels per row, causing a buffer overflow.

## Reproduction

(This may only happen on some hardware. I'm running on an x64-based Windows 11 PC with an AMD Ryzen processor)

```c
#include "raymedia.h"

const char* ExampleTitle = "Example 01 - Basics";

const int   ScreenWidth = 1920 / 2;
const int   ScreenHeight = 1080 / 2;
const char* MovieFile = ASSETS_PATH"examples/broken1.mp4"; // You may need to change this line depending on how you load assets

int main(int argc, char** argv)
{
    InitWindow(ScreenWidth, ScreenHeight, TextFormat("raylib-media | %s", ExampleTitle));
    SetWindowState(FLAG_WINDOW_RESIZABLE);
    SetTargetFPS(60);
    InitAudioDevice();

    MediaStream videoMedia = LoadMedia(MovieFile);

    if (!IsMediaValid(videoMedia))
    {
        TraceLog(LOG_ERROR, "Failed to load media file: %s", MovieFile);
        CloseAudioDevice();
        CloseWindow();
        return -1;
    }

    SetMediaLooping(videoMedia, true);

    while (!WindowShouldClose())
    {
        UpdateMedia(&videoMedia);

        BeginDrawing();
        ClearBackground(DARKPURPLE);

        float scale = 1.0f;
        int displayWidth = videoMedia.videoTexture.width;
        int displayHeight = videoMedia.videoTexture.height;
        
        if (displayWidth > GetScreenWidth() || displayHeight > GetScreenHeight()) {
            float scaleX = (float)GetScreenWidth() / displayWidth;
            float scaleY = (float)GetScreenHeight() / displayHeight;
            scale = (scaleX < scaleY) ? scaleX : scaleY;
            
            displayWidth = (int)(displayWidth * scale);
            displayHeight = (int)(displayHeight * scale);
        }
        
        const int videoPosX = (GetScreenWidth() - displayWidth) / 2;
        const int videoPosY = (GetScreenHeight() - displayHeight) / 2;

        Rectangle sourceRect = {0, 0, (float)videoMedia.videoTexture.width, (float)videoMedia.videoTexture.height};
        Rectangle destRect = {(float)videoPosX, (float)videoPosY, (float)displayWidth, (float)displayHeight};
        Vector2 origin = {0, 0};

        DrawTexturePro(videoMedia.videoTexture, sourceRect, destRect, origin, 0, WHITE);

        EndDrawing();
    }

    UnloadMedia(&videoMedia);
    CloseAudioDevice();
    CloseWindow();

    return 0;
}

```

#### The video where rightmost pixels are skipped (1078x2316)

https://github.com/user-attachments/assets/34cf3d45-98cd-41a7-ac50-834ab716fb8d

#### The video that causes buffer overflow (1068x2316)

https://github.com/user-attachments/assets/e2af8a2d-5339-47c5-9188-b50f746dc99a

### Example of skipping pixels per row (1078x2316; vertical black bar on the right of the video)

Image

### Example of buffer overflow (1068x2316)

https://github.com/user-attachments/assets/541de4ef-c320-49e0-ba6f-19bfc8b244f0

This seems to happen because `sws_scale` expects the output buffer's stride/linesize per row of the image to be 16-byte aligned at a minimum (that number may be larger though on different hardware I think. I'm running on an x64-based Windows PC with an AMD Ryzen processor). I don't think FFmpeg clearly documents this anywhere, but it's mentioned here and there online:
- "Some parts of FFmpeg, notably libavcodec, require aligned linesizes[]... For swscale/avfilter, I believe there is no absolute requirement, but you're recommended to still make it 32." https://stackoverflow.com/questions/35678041/what-is-linesize-alignment-meaning
- "The underlying issue is that the alignment passed to a bunch of libav functions is 1, but for sws_scale to work in general it is apparently supposed to be 32": https://github.com/OpenShot/libopenshot/issues/576
    - https://stackoverflow.com/questions/31253485/how-do-you-resize-an-avframe/31270501#31270501
- OBS also had this bug with YUV-to-RGB conversion
    - https://github.com/obsproject/obs-studio/issues/3062
    - https://github.com/obsproject/obs-studio/pull/2836
        - Fixes https://obsproject.com/mantis/view.php?id=1032
        - Fixes https://obsproject.com/mantis/view.php?id=1177
- > With the 4.3 release, swscale now crashes if provided with an output buffer that is not 16 bytes aligned for yuv2rgb conversions. It used to work in previous releases [*](https://trac.ffmpeg.org/ticket/8747)
- https://trac.ffmpeg.org/ticket/10514

I also tested this experimentally: ([Google Sheets link](https://docs.google.com/spreadsheets/d/1I4Msq5oENkQT2wsVAEyQue7ZfxpAKwwOr0Dv74kU7eA/edit?usp=sharing)):

Image

The data shows how most files crash when `(W * 3) % 48 != 0` (and for the few cases where that's not true, those are the cases where not all pixels are processed, causing the black vertical bar on the right of the video). I believe all of this has something to do with [the assembly (at least on x86) writing in 48-byte chunks](https://github.com/FFmpeg/FFmpeg/blob/master/libswscale/x86/yuv_2_rgb.asm), and something to do with [this code](https://github.com/FFmpeg/FFmpeg/blob/master/libswscale/x86/yuv2rgb.c#L44), but I didn't dig much deeper since it didn't feel necessary.

I opened a PR to fix these issues here: https://github.com/cloudofoz/raylib-media/pull/11

### PR DESCRIPTION
**Pull request by shanrauf**
Closes #12 

# What

- Makes the linesize 32-byte aligned for the output buffer used for video frame conversion
- Memcopies that output into `videoOutputImage.data` (which has no padding bytes between rows)

# Why

`sws_scale` expects aligned linesizes or else certain videos will cause buffer overflows or missing pixels in the output image when writing directly to `videoOutputImage.data`

### CODE REVIEW

**Comment by shanrauf** [comment]
@cloudofoz Mind reviewing this?

File: src/rmedia.c [hunk 1]
```diff
@@ -702,7 +704,16 @@ MediaContext* LoadMediaContext(const char* fileName, MediaStreamReader streamRea
 				ctx->videoOutputImage.mipmaps = 1;
 				ctx->videoOutputImage.format  = PIXELFORMAT_UNCOMPRESSED_R8G8B8;
 
-				ImageClearBackground(&ctx->videoOutputImage, BLANK),
+				ImageClearBackground(&ctx->videoOutputImage, BLANK);
+
+				int allocatedBytes = av_image_alloc(ctx->alignedRgbData, ctx->alignedRgbLinesize, codecCtx->width, codecCtx->height, AV_PIX_FMT_RGB24, 32);
```
Comment (shanrauf) [inline src/rmedia.c:709]: This allocates a single contiguous buffer, and the other pointers (which will always be `NULL` anyway for RGB24) point into that buffer; [documentation ref](https://ffmpeg.org/doxygen/6.0/group__lavu__picture.html#ga841e0a89a642e24141af1918a2c10448))

image

File: src/rmedia.c [hunk 2]
```diff
@@ -170,6 +170,8 @@ typedef struct MediaContext
 	// Video stream-related fields
 	struct SwsContext* swsContext;              // Video resampling and scaling context
 	Image videoOutputImage;                     // Image buffer holding the decoded video frame, uploaded to [MediaStream].videoTexture
+	uint8_t *alignedRgbData[4];                 // Pointers to the RGB buffers used for YUV-to-RGB frame conversion
+	int alignedRgbLinesize[4];                  // Linesizes for the RGB buffers used for YUV-to-RGB frame conversion
```
Comment (shanrauf) [inline src/rmedia.c]: (It just occurred to me that my comments suggest that the input video being converted to RGB will always be in YUV format, but that isn't necessarily true. I can change it after getting your feedback on the PR)

**Comment by cloudofoz** [comment]
> @cloudofoz Mind reviewing this?

Hi @shanrauf, thanks a lot for the detailed issue and all the work you've put into this. 🙏 I'm going to take a proper look, test it both with and without the fix, and follow up soon. Really appreciate the effort you put into this!

File: src/rmedia.c (hunk 2 above)
Comment (cloudofoz) [reply src/rmedia.c:174]: @shanrauf I've tested the videos you submitted and can confirm that I’m seeing the same issues here on Windows 11 with an Intel CPU. Your patch solves both the crash and the pixel clipping, great work! Definitely a tricky bug.

> (It just occurred to me that my comments suggest that the input video being converted to RGB will always be in YUV format, but that isn't necessarily true. I can change it after getting your feedback on the PR)

If you don’t mind updating the code to apply the alignment fix only when the input is actually YUV, that would make the solution even more robust.

Once that's in, I’ll go ahead and merge your PR right after. Thanks again for the excellent report and fix 🙏

**Comment by cloudofoz** [comment]
@shanrauf I've tested the videos you submitted and can confirm that I’m seeing the same issues here on Windows 11 with an Intel CPU. Your patch solves both the crash and the pixel clipping, great work! Definitely a tricky bug.

> (It just occurred to me that my comments suggest that the input video being converted to RGB will always be in YUV format, but that isn't necessarily true. I can change it after getting your feedback on the PR)

If you don’t mind updating the code to apply the alignment fix only when the input is actually YUV, that would make the solution even more robust.

Once that's in, I’ll go ahead and merge your PR right after. Thanks again for the excellent report and fix 🙏

File: src/rmedia.c [hunk 3]
```diff
@@ -1969,7 +1985,17 @@ int  AVProcessVideoFrame(const MediaStream* media)
 	const int rgbLineSize = codec->width * 3;
 
 	// Convert the frame to RGB
-	sws_scale(ctx->swsContext, (const uint8_t* const*)ctx->avFrame->data, ctx->avFrame->linesize, 0, codec->height, (uint8_t* const*) &ctx->videoOutputImage.data, &rgbLineSize);
+	int ret = sws_scale(ctx->swsContext, (const uint8_t* const*)ctx->avFrame->data, ctx->avFrame->linesize, 0, codec->height, ctx->alignedRgbData, ctx->alignedRgbLinesize);
+	if (ret <= 0) {
+		TraceLog(LOG_ERROR, "MEDIA: Failed to convert frame");
+		return -1;
```
Comment (cloudofoz) [inline src/rmedia.c:1991]: Just noting: I'll probably add a more specific error code here after the merge.

**Comment by shanrauf** [comment]
@cloudofoz I did some more testing, and there are at least 3 pixel formats (variations of YUV) that crash on `main` (there may be more). Instead of trying to find all the breaking ones and explicitly listing them (there are a lot of supported formats [here](https://ffmpeg.org/doxygen/3.3/pixfmt_8h.html)), maybe it'd be better to keep the 32-byte alignment for all possible inputs to avoid issues? (assuming that's fine, I went ahead and removed mentions of YUV from the code and the PR is ready again for review)

EXCEL_eEPxPlZg6h

[raylib-media pixel formats experiment.xlsx](https://github.com/user-attachments/files/19673952/raylib-media.pixel.formats.experiment.xlsx)

**Comment by cloudofoz** [comment]
Better safe than sorry! You definitely made the right call. I'm merging your fix now.

I was also thinking about possible optimizations. Right now, the pipeline looks like this:

`[Decoded AVFrame] → (sws_scale) → [Aligned RGB buffer] → (memcpy) → [raylib Image data] → (UpdateTexture) → [GPU Texture]`

It would be nice if we could eventually eliminate one of those steps, maybe by uploading the aligned RGB buffer directly, if the stride matches. But that's something for later - what's most important is that the code is now much more robust and handles these tricky edge cases safely.

Thanks again for the in-depth analysis, I really appreciated both the fix and the clarity you brought to the issue!

C.
